src/components/LeafletMap.jsx, src/context/FilterProjectsContext.jsx, src/styles/globalStyles.js
=> Make pins show up again

src/components/Header/Header.jsx
Update to the following order and text:
- Dashboard Highlights
- Data Disclaimer
- Data Protection and Following
- Contact Us
=> M927: Update overflow menu

src/components/MapAndTableControls/MapAndTableControls.jsx, src/components/MapAndTableControls/components/FilterIndicatorPill.jsx
Built to specifications[ in ticket ](https://trello.com/c/DwZux8Jf/1029-update-tool-bar-layout?filter=label:dash%20app)
=> 1029 update toolbar layout

src/App.jsx, src/components/MapAndTableControls/MapAndTableControls.jsx, src/components/MermaidDash/MermaidDash.jsx, src/components/MermaidDash/components/LoadingIndicator.jsx, src/components/MetricsPane/MetricsPane.jsx, src/components/MetricsPane/MetricsPane.styles.js
[Ticket](https://trello.com/c/MenfSCjr/813-overview-metric-pane?filter=label:dash%20app)
Note: the loading indicator width on mobile is not as shown in the mockups, and while I did some loading indicator work, I am treating the width issue as out-of-scope for now.
=> 813 metrics pane 1

src/components/MetricsPane/MetricsPane.jsx, src/components/MetricsPane/charts/AggregateHabitatComplexity.jsx, src/styles/dashboardOnlyTheme.js
⚠️ ⚠️ ⚠️ **NOTE TO SELF: CHANGE BASE BRANCH TO DEVELOP BEFORE MERGE** ⚠️ ⚠️ ⚠️
Changes: 
- add aggregate habitat complexity chart
- update theme to have default marker colour + refactor
=> 1011 aggregate habitat complexity

src/components/MetricsPane/SelectedProjectMetrics.jsx, src/components/MetricsPane/SelectedSiteMetrics.jsx, src/components/MetricsPane/SelectedSiteMetrics.styles.js
trello: https://trello.com/c/3orETn0O/1179-add-datasharing-subcard-to-the-metric-pane
=> [M1179] Add datasharing subcard to the metric pane

src/components/MermaidDash/MermaidDash.jsx, src/hooks/useLocalStorage.js
Trello: https://trello.com/c/59wgq7J6/1172-start-with-the-filter-pane-closed-on-the-dashboard-and-remember-pane-states
=> [M1172] Add local storage hook, and store filter panel state.

src/components/MapAndTableControls/MapAndTableControls.jsx
Trello: https://trello.com/c/nHptUySv/1154-zoom-to-extent-of-filtered
=> [M1154] Prevent whole world zoom for IDL locations.

src/components/MetricsPane/MetricsPane.jsx, src/components/MetricsPane/MetricsPane.styles.js
Trello: https://trello.com/c/xd98O1Ie/1246-move-follow-button-position
=> [M1246] The Follow Button Disappear on Dev

src/components/FilterPane/FilterPane.jsx, src/components/FilterPane/FilterPane.styles.js
Trello: https://trello.com/c/29OSjWU3/872-prompt-the-user-to-login-when-viewing-private-data
Add log in to view in Filter pane to see your data.
=> [M872] Prompt the user to login when viewing private data.

src/components/MetricsPane/charts/TimeSeriesBenthicCover.jsx, src/components/MetricsPane/charts/TimeSeriesBleaching.jsx, src/components/MetricsPane/charts/TimeSeriesFishBiomass.jsx, src/components/MetricsPane/charts/TimeSeriesHabitatComplexity.jsx
Trello: https://trello.com/c/8thEBO54/1268-dashboard-chart-improvements
=> [M1268] - Time Series Chart improvements

src/components/MetricsPane/charts/AggregateFishBiomas.jsx
Trello: https://trello.com/c/ZFH5DoCo/1264-bin-surveys-with-a-biomass-of-5000-kg-ha-for-fish-biomass-visualization
=> [M1264] Bin surveys with a biomass of 5,000+ kg/ha for Fish Biomass visualization

src/components/MermaidDash/MermaidDash.jsx, src/components/MermaidDash/MermaidDash.styles.js
Trello: https://trello.com/c/0CdgqKjN/1270-new-download-button-in-filter-pane
=> [M1270] Set up download button in filter panel

src/components/FilterPane/FilterPane.jsx, src/components/MetricsPane/MetricsPane.jsx, src/components/MetricsPane/charts/AggregateBleaching.jsx, src/components/MetricsPane/charts/AggregateFishBiomas.jsx, src/components/MetricsPane/charts/AggregateHabitatComplexity.jsx, src/components/MetricsPane/charts/AggregateHardCoralCover.jsx, src/components/MetricsPane/charts/Charts.styles.js, src/components/MetricsPane/charts/NoDataChartView.jsx, src/components/MetricsPane/charts/PrivateChartView.jsx, src/components/MetricsPane/charts/SampleEventBenthicPlot.jsx, src/components/MetricsPane/charts/SampleEventBleachingPlot.jsx, src/components/MetricsPane/charts/SampleEventBleachingSeverityPlot.jsx, src/components/MetricsPane/charts/SampleEventFishBiomassPlot.jsx, src/components/MetricsPane/charts/SampleEventHabitatComplexityPlot.jsx, src/components/MetricsPane/charts/TimeSeriesBenthicCover.jsx, src/components/MetricsPane/charts/TimeSeriesBleaching.jsx, src/components/MetricsPane/charts/TimeSeriesFishBiomass.jsx, src/components/MetricsPane/charts/TimeSeriesHabitatComplexity.jsx, src/components/TableView/TableView.jsx, src/constants/language.js
Trello: https://trello.com/c/9TY3AO4y/1212-private-and-no-data-data-vis-cards
note: the contextual help button will be in other ticket
=> [M1212] Private- and no-data data vis cards

src/components/FilterPane/FilterPane.jsx, src/constants/constants.js, src/context/FilterProjectsContext.jsx
Trello: https://trello.com/c/lavY71hq/1273-add-project-with-no-data-filter-to-url-parameters?filter=label:dash%20app
=> [M1273] Add "project with no data" filter to URL parameters.

src/components/MetricsPane/MetricsPane.jsx
Trello: https://trello.com/c/lwEYAaSG/1295-clear-the-selected-site-in-metric-pane-if-it-gets-filtered-out
=> [M1295] Clear the selected site in metric pane if it gets filtered out.

src/components/MetricsPane/MetricsPane.jsx, src/components/MetricsPane/MetricsPane.styles.js, src/components/MetricsPane/SelectedProjectMetrics.styles.js, src/components/MetricsPane/SelectedSiteMetrics.styles.js
Trello: https://trello.com/c/6SCV6wdF/1265-dynamically-adjust-position-of-metric-pane-collapse-and-follow-my-map-buttons
=> [M1265] Dynamically adjust position of metric pane collapse and follow-my-map buttons

src/components/MetricsPane/charts/AggregateFishBiomas.jsx, src/components/MetricsPane/charts/AggregateHardCoralCover.jsx, src/components/MetricsPane/charts/SampleEventBenthicPlot.jsx, src/components/MetricsPane/charts/SampleEventBleachingPlot.jsx, src/components/MetricsPane/charts/SampleEventBleachingSeverityPlot.jsx, src/components/MetricsPane/charts/SampleEventFishBiomassPlot.jsx, src/components/MetricsPane/charts/SampleEventHabitatComplexityPlot.jsx, src/components/MetricsPane/charts/TimeSeriesBenthicCover.jsx, src/components/MetricsPane/charts/TimeSeriesBleaching.jsx, src/styles/dashboardOnlyTheme.js
All feedbacks can be viewed in Trello ticket https://trello.com/c/G88MAYUC/1283-more-chart-feedbacks.
=> [M1283] Charts Feedback & Improvements.

src/components/Header/components/ShareViewModal.jsx, src/components/generic/Modal.jsx, src/constants/language.js
Revise the text and button behavior in the data sharing modal. The button now indicates when the URL has been copied, and unnecessary modal description text has been removed.
=> [M925] Update data sharing modal text and button functionality

src/components/MetricsPane/MetricsPane.jsx, src/components/MetricsPane/MetricsPaneChartTabs.jsx, src/constants/constants.js
Trello: https://trello.com/c/JpdgWSgg/1266-preserve-plot-selection-in-query-params
=> [M1266] Preserve plot selection in query params

src/components/Header/Header.jsx, src/components/Header/Header.styles.js, src/components/Header/components/ShareViewModal.jsx, src/components/generic/Modal.jsx
Trello: https://trello.com/c/zziAW4aj/1307-no-overflow-login-menu-on-mobile
=> [M1307] No overflow/login menu on mobile

src/components/MermaidDash/components/DownloadGFCRModal.jsx, src/components/MermaidDash/components/DownloadModal.jsx, src/constants/language.js
Trello: https://trello.com/c/z11iYTR1/1308-change-error-modal-to-toast-message-for-download-modal
=> [M1308] Change error modal to toast message for Download Modal

src/components/FilterPane/FilterPane.jsx, src/components/FilterPane/FilterPane.styles.js, src/components/MapAndTableControls/MapAndTableControls.jsx, src/components/MaplibreMap.jsx, src/components/MermaidDash/MermaidDash.jsx, src/components/MermaidDash/MermaidDash.styles.js
Trello: https://trello.com/c/2iJGFij2/1312-updates-to-the-filter-pane-control
=> [M1312] Updates to the filter pane control.

src/components/FilterPane/FilterPane.jsx, src/components/MapAndTableControls/MapAndTableControls.jsx, src/components/MaplibreMap.jsx, src/components/MermaidDash/MermaidDash.jsx, src/components/MermaidDash/components/DownloadGFCRModal.jsx, src/components/MermaidDash/components/DownloadModal.jsx, src/components/MetricsPane/MetricsPane.jsx, src/components/MetricsPane/SelectedProjectMetrics.jsx, src/components/MetricsPane/SelectedSiteMetrics.jsx, src/components/ProjectTableDownload/ProjectTableDownload.jsx, src/components/TableView/TableView.jsx, src/components/generic/AutocompleteCheckbox.jsx, src/constants/constants.js, src/constants/language.js, src/context/FilterProjectsContext.jsx, src/helperFunctions/selectedSite.js
Remove project list, add project select input, and refactor all affected changes.
Trello: https://trello.com/c/67xUcmdF/1300-update-project-dropdown-to-work-the-same-as-countries-orgs
=> [M1300] Update project dropdown to work the same as countries/orgs

src/components/FilterPane/FilterPane.jsx, src/components/Header/Header.jsx, src/components/MetricsPane/SelectedSiteMetrics.jsx, src/components/MetricsPane/charts/SampleEventBenthicPlot.jsx, src/components/MetricsPane/charts/SampleEventBleachingPlot.jsx, src/components/MetricsPane/charts/SampleEventBleachingSeverityPlot.jsx, src/components/MetricsPane/charts/SampleEventFishBiomassPlot.jsx, src/components/MetricsPane/charts/TimeSeriesBenthicCover.jsx, src/components/ProjectTableDownload/ProjectTableDownload.jsx, src/constants/language.js
Trello: https://trello.com/c/weNOhTb4/1310-text-changes
=> [M1310] Text Changes

src/components/MermaidDash/components/DownloadGFCRModal.jsx, src/components/MermaidDash/components/DownloadModal.jsx, src/components/MetricsPane/MetricsPane.jsx, src/helperFunctions/pluralize.js
Trello: https://trello.com/c/nHREzsKP/1321-use-singular-word-when-theres-only-one-in-metrics-pane
=> [M1321] Use singular word when there's only one in metrics pane

src/App.jsx, src/components/generic/toast.js
Trello: https://trello.com/c/FaOnDb8E/1318-use-the-same-toast-notification-style-and-library-as-collect
There are current 2 toasts in the new dash apps
=> [M1318] Use the same toast notification style and library as Collect.

src/components/MermaidDash/MermaidDash.jsx, src/components/MermaidDash/components/LoadingBar.jsx, src/components/MermaidDash/components/LoadingIndicator.jsx, src/components/MetricsPane/MetricsPane.jsx, src/components/MetricsPane/MetricsPane.styles.js
Trello: https://trello.com/c/hStrKCWA/1327-update-the-loading-indicator-to-make-it-more-obvious
=> [M1327] Update the loading indicator to make it more obvious

src/components/FilterPane/FilterPane.jsx, src/components/FilterPane/FilterPane.styles.js, src/components/generic/MermaidMui.jsx, src/styles/mediaQueries.js
- Remove margin right, and Refactor FilterPane component by removing un…used ShowMoreFiltersContainer and adjusting media query breakpoint for medium desktop.
- _Extra: remove max width on select input affecting SelectedSiteMetric component where the width isn't expanding as full width as it needs to._
Trello: https://trello.com/c/liF7Yea4/1343-update-the-more-filters-section-of-the-filters-pane?filter=label:dash%20app
=> [M1343] Update the more filters section of the filters pane.

src/components/generic/Table/PageSelector/PageSelector.jsx
Trello: https://trello.com/c/TqlaBLxj/1335-update-pagination-ui-in-dashboard
=> [M1335] Update pagination UI in dashboard

src/assets/icons.jsx, src/components/MetricsPane/charts/AggregateBleaching.jsx, src/components/MetricsPane/charts/AggregateFishBiomas.jsx, src/components/MetricsPane/charts/AggregateHabitatComplexity.jsx, src/components/MetricsPane/charts/AggregateHardCoralCover.jsx, src/components/MetricsPane/charts/Charts.styles.js, src/components/MetricsPane/charts/HardCoralInfoModal.jsx, src/components/MetricsPane/charts/SampleEventBenthicPlot.jsx, src/components/MetricsPane/charts/SampleEventBleachingPlot.jsx, src/components/MetricsPane/charts/SampleEventBleachingSeverityPlot.jsx, src/components/MetricsPane/charts/SampleEventFishBiomassPlot.jsx, src/components/MetricsPane/charts/SampleEventHabitatComplexityPlot.jsx, src/components/MetricsPane/charts/TimeSeriesBenthicCover.jsx, src/components/MetricsPane/charts/TimeSeriesBleaching.jsx, src/components/MetricsPane/charts/TimeSeriesFishBiomass.jsx, src/components/MetricsPane/charts/TimeSeriesHabitatComplexity.jsx, src/constants/language.js, src/helperFunctions/pluralize.js, src/styles/plotlyChartTheme.js
Trello: https://trello.com/c/DiDTP5Z9/1368-revise-hard-coral-cover-aggregate-plot-based-on-feb-2025-dashboard-feedback?filter=label:dash%20app
=> [M1368] [M1370] [M1371] & [M1372] All charts improvements based on user feedbacks

src/components/MermaidDash/MermaidDash.styles.js, src/components/generic/Modal.jsx, src/styles/mediaQueries.js
https://trello.com/c/6KZDIPmH/1397-set-the-mobile-breakpoint-to-1080px
=> [M1397-hot-fix]  

src/components/Header/components/DataDisclaimer.jsx, src/components/Header/components/ShareViewModal.jsx, src/components/MermaidDash/components/DataSharingInfoModal.jsx, src/components/MermaidDash/components/ErrorFetchingModal.jsx, src/components/MermaidDash/components/ExportGFCRModal.jsx, src/components/MermaidDash/components/ExportModal.jsx, src/components/MermaidDash/components/ExportTableView.jsx, src/components/MetricsPane/charts/HardCoralInfoModal.jsx, src/components/generic/Modal.jsx, src/styles/theme.js
https://trello.com/c/VAe93YNJ/1395-updated-to-the-download-export-modal
=> [M1395-hot-fix]

src/components/MetricsPane/ContactOrUserIcon.jsx, src/components/MetricsPane/SelectedProjectMetrics.jsx, src/components/MetricsPane/SelectedProjectMetrics.styles.js, src/components/MetricsPane/SelectedSiteMetrics.jsx
- Add contact admins or user icon on Site Metadata tab
- Also add the same icons to Project metric pane
=> [M1438] Add contact admins or user icon on Site Metadata tab

src/components/MaplibreMap.jsx
**New feature:**
- Add bbox param support when map load.
- Map prioritize zoom to bbox when its available and remove bbox param when map is done done loading.
**Example url link with localhost**
http://localhost:3030/?bbox=174.61584600000003,-21.742291,181.769272,-16.1057
=> [M1459] bbox param support for map load

src/components/MetricsPane/charts/TimeSeriesBenthicCover.jsx, src/components/MetricsPane/charts/TimeSeriesBleaching.jsx, src/components/MetricsPane/charts/TimeSeriesFishBiomass.jsx, src/components/MetricsPane/charts/TimeSeriesHabitatComplexity.jsx, src/helperFunctions/chartHelpers.js
Add fix to ensure all time series chart with fewer than 3 years limit should have category chart type
=> fix:  [M1606] Time series chart x axis has incorrect tick marks
